chore: update installation doc for 1.0.0 release
oras-project/oras-www pull request #132
Opened 2023-03-20 13:07 UTC by qweeah

This PR updates the installation doc.

2023-03-20 13:16 UTC, TerryHowe approved these changes
LGTM

2023-03-21 01:34 UTC, FeynmanZhou commented on docs/CLI/index.md
> +VERSION="1.0.0"
@qweeah I think we need to update this section with Homebrew installation as this has been upgraded in https://github.com/Homebrew/homebrew-core/pull/126141

2023-03-21 01:34 UTC, FeynmanZhou requested changes
PTAL at my comment. Thanks

2023-03-21 01:37 UTC, SteveLasker approved these changes
LGTM

2023-03-21 07:12 UTC, FeynmanZhou approved these changes
LGTM

2023-03-21 07:12 UTC, merged