feat: add adopters page
oras-project/oras-www pull request #157
Opened 2023-05-07 09:33 UTC by asmitbm

This page contains a list of projects leveraging ORAS, as well as registries that are known to support [OCI Artifacts](https://github.com/opencontainers/artifacts).

2023-05-07 15:19 UTC, asmitbm commented
Cc: @FeynmanZhou 

The adopters page is almost complete, only the content part of this page is remaining. After that, this PR will be ready for review.

2023-05-19 03:54 UTC, FeynmanZhou commented on static/adopters/data.js
> +const projects = [
Could you double check the project intro on each card? For example, the Helm project intro is not correct
![image](https://github.com/oras-project/oras-www/assets/40452856/11a1650f-d7be-4508-8596-3d3b66530673)

2023-05-19 03:54 UTC, FeynmanZhou requested changes
PTAL

2023-05-19 04:17 UTC, asmitbm commented
> PTAL

Actually Helm is just mentioned as package manager for Kubernetes, hence I researched more and add that info. Will change it to product docs now.

2023-05-26 14:56 UTC, FeynmanZhou approved these changes
LGTM

2023-05-26 14:56 UTC, merged