issue #152: New depandabot.yml
oras-project/oras-www pull request #160
Opened 2023-05-14 06:45 UTC by RickDeb2004

Dependabot will now automatically create pull requests to update outdated dependencies.
[

2023-05-14 16:55 UTC, TerryHowe requested changes
I think this needs to be up one dir like https://github.com/oras-project/oras/blob/main/.github/dependabot.yml and have the copyright I guess.

Also, you need to sign the DCO.

Thanks!

2023-05-15 06:40 UTC, RickDeb2004 commented
> I think this needs to be up one dir like https://github.com/oras-project/oras/blob/main/.github/dependabot.yml and have the copyright I guess.
> 
> Also, you need to sign the DCO.
> 
> Thanks!

Sir ,I have added the signed off message still DCO check is not running ,pls check this issue
and I think this needs to be up one dir like https://github.com/oras-project/oras/blob/main/.github/dependabot.yml I can't understand this one ,pls elaborate it

2023-05-15 11:24 UTC, TerryHowe requested changes

2023-05-15 11:24 UTC, TerryHowe commented on .github/ISSUE_TEMPLATE/depandabot.yml
> +# Copyright The ORAS Authors.
I'm prettu sure this file should be in the `.github` directory

2023-05-15 11:24 UTC, TerryHowe commented on .github/ISSUE_TEMPLATE/depandabot.yml
> +# Copyright The ORAS Authors.
Your first commit is not signed off and I think that is causing the DCO problem. You might want to squash the 3 commits into one like https://stackoverflow.com/questions/5189560/how-do-i-squash-my-last-n-commits-together and `git commit -signoff` on the one commit. After that force push the changes

2023-05-16 06:28 UTC, shizhMSFT commented
Closed by #162

2023-05-16 06:28 UTC, closed without merging