chore: update dependabot.yml
oras-project/oras-www pull request #169
Opened 2023-05-17 08:47 UTC by asmitbm

Update dependabot.yml file to update dependencies weekly. This will help us review PRs and maintain the dependencies in a neater way.

Also added `ignore` key to ignore the major version upgrades of dependencies (#168, #166, #164) which might cause breaking down of the website. This will also help reduce unnecessary PRs. Security updates are unaffected by this setting. 

More info here: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#specifying-dependencies-and-versions-to-ignore

2023-05-17 12:22 UTC, TerryHowe requested changes

2023-05-17 12:22 UTC, TerryHowe commented on .github/dependabot.yml
> +        update-types: ["version-update:semver-major"]
Minor and bug versions will have CVE patches, we want the bot for that

2023-05-17 13:57 UTC, TerryHowe commented on .github/dependabot.yml
> +        update-types: ["version-update:semver-major"]
Ah, sorry missed the `ignore` part

2023-05-17 13:58 UTC, TerryHowe reviewed
Why are we running versions with old major versions though?

2023-05-17 14:00 UTC, asmitbm commented
> Why are we running versions with old major versions though?

Answered that query here: https://github.com/oras-project/oras-www/pull/164#issuecomment-1551356878

2023-05-17 15:52 UTC, sajayantony approved these changes

2023-05-19 03:50 UTC, FeynmanZhou approved these changes
LGTM

2023-05-19 03:50 UTC, merged