updated oras_blob_fetch.mdx
oras-project/oras-www pull request #180
Opened 2023-05-20 13:30 UTC by RickDeb2004

Closes: #130

By using jq and pv, one can show the content downloading progress when using ORAS. This demonstrates how to fetch a blob with a specific reference, determine its size using jq, and use pv to display the progress while redirecting the output to a file named layer.bin.

```
$ blob_ref=ghcr.io/oras-project/oras@sha256:74529e03eae02d1fff5c05e9a6ec2089e1f5ae96421169c29a7c165346e042e4
$ size=$(oras blob fetch --descriptor $blob_ref | jq -r .size)
$ oras blob fetch $blob_ref --output - | pv -s $size > layer.bin
```

2023-05-22 11:52 UTC, TerryHowe commented on docs/CLI_Reference/oras_blob_fetch.mdx
> +fetch a blob with a specific reference, determine its size using jq, and use pv to display the progress while redirecting the output to a file named layer.bin
My feeling is this should be the last example since it is the most complicated.

2023-05-22 12:50 UTC, RickDeb2004 commented
done @TerryHowe

2023-05-24 15:05 UTC, RickDeb2004 commented on docs/CLI_Reference/oras_blob_fetch.mdx
> +
> Make this the last example

@TerryHowe Done

2023-05-24 15:06 UTC, RickDeb2004 commented on docs/CLI_Reference/oras_blob_fetch.mdx
> +
> > Make this the last example
> 
> @TerryHowe Done

@TerryHowe Sorry for misinterpreting last time

2023-05-25 12:43 UTC, TerryHowe approved these changes
/lgtm

2023-05-31 12:12 UTC, TerryHowe commented
@asmitbm thoughts?

2023-05-31 17:31 UTC, asmitbm requested changes

2023-05-31 17:31 UTC, asmitbm commented on docs/CLI_Reference/oras_blob_fetch.mdx
> +Fetch a blob with a specific reference, determine its size using jq, and use pv to display the progress while redirecting the output to a file named layer.bin
```suggestion
Fetch a blob with a specific reference, determine its size using `jq`, and use `pv` to display the progress while redirecting the output to a file named `layer.bin`:
```
I think including jq, pv. and layer.bin in code line will highlight it more. Just a nitpick. Everything else looks good.

2023-05-31 17:35 UTC, asmitbm approved these changes

2023-05-31 17:35 UTC, asmitbm commented
LGTM

2023-05-31 17:35 UTC, merged