add formatted output user manual
oras-project/oras-www pull request #356
Opened 2024-06-25 23:58 UTC by FeynmanZhou

2024-06-26 00:49 UTC, sajayantony requested changes

2024-06-26 00:49 UTC, sajayantony commented on versioned_docs/version-1.2/how_to_guides/format_output.mdx
> +> [!NOTE]
something might be off here - 
![image](https://github.com/oras-project/oras-www/assets/1821104/3e7f50ae-7d19-4a51-aaaa-3c7e10b4535f)

I think the other notes also need to be fixed.

2024-06-27 14:52 UTC, TerryHowe requested changes

2024-06-27 14:52 UTC, TerryHowe commented on versioned_docs/version-1.2/how_to_guides/format_output.mdx
> +ORAS allows to use `--output` to output a file or directory in the filesystem. To enable users to format the metadata output of ORAS commands and compute figures based on the formatted output, these
```suggestion
The ORAS command allows users to format the metadata output and perform computations on data based on the formatted output. The ORAS command also allows the `--output` option to write to a file or directory.
```

2024-06-27 14:52 UTC, TerryHowe commented on versioned_docs/version-1.2/how_to_guides/format_output.mdx
> +- Use `--format <DATA_FORMAT>` to format metadata output of ORAS commands into different formats including prettified JSON, tree, table view, and Go template, i.e. `--format json|tree|table|go-templa
```suggestion
- Use `--format <DATA_FORMAT>` to format metadata output of ORAS commands into different formats including prettified JSON, tree, table view, and Go template, i.e. `--format json|tree|table|go-template`. It supports computing figures within the template using [Sprig](http://masterminds.github.io/sprig/) functions. This is the primary and recommended usage.
```

2024-06-27 14:52 UTC, TerryHowe commented on versioned_docs/version-1.2/how_to_guides/format_output.mdx
> +Note that both `--format` and `--template` are marked as "Experimental" in its first iteration v1.2.0.
```suggestion
:::note

Both `--format` and `--template` are marked as "Experimental" in its first iteration v1.2.0.

:::
```

2024-06-27 14:52 UTC, TerryHowe commented on versioned_docs/version-1.2/how_to_guides/format_output.mdx
> +ORAS allows to use the `--format` flag to format metadata output into structured data (e.g. JSON) and optionally use the `--template` with the [Go template](https://pkg.go.dev/text/template) to manip
```suggestion
Use the `--format` flag to format metadata output into structured data (e.g. JSON) and optionally use the `--template` option with a [Go template](https://pkg.go.dev/text/template) to manipulate the output data. See sample usages in several commands below.
```

2024-06-27 14:52 UTC, TerryHowe commented on versioned_docs/version-1.2/how_to_guides/format_output.mdx
> +`--output -` and `--format` can not be used at the same time due to conflicts.
```suggestion
The `--output -` option for standard output cannot be used with the `--format` option due to conflicts.
```

2024-06-27 14:53 UTC, TerryHowe commented
This was originally written as a requirements document and just needs some updates to change the tone.

2024-07-02 15:50 UTC, FeynmanZhou commented on versioned_docs/version-1.2/how_to_guides/format_output.mdx
> +ORAS allows to use `--output` to output a file or directory in the filesystem. To enable users to format the metadata output of ORAS commands and compute figures based on the formatted output, these
Updated

2024-07-02 15:50 UTC, FeynmanZhou commented on versioned_docs/version-1.2/how_to_guides/format_output.mdx
> +- Use `--format <DATA_FORMAT>` to format metadata output of ORAS commands into different formats including prettified JSON, tree, table view, and Go template, i.e. `--format json|tree|table|go-templa
Updated

2024-07-02 15:50 UTC, FeynmanZhou commented on versioned_docs/version-1.2/how_to_guides/format_output.mdx
> +Note that both `--format` and `--template` are marked as "Experimental" in its first iteration v1.2.0.
Updated

2024-07-02 15:51 UTC, FeynmanZhou commented on versioned_docs/version-1.2/how_to_guides/format_output.mdx
> +ORAS allows to use the `--format` flag to format metadata output into structured data (e.g. JSON) and optionally use the `--template` with the [Go template](https://pkg.go.dev/text/template) to manip
Updated

2024-07-02 15:51 UTC, FeynmanZhou commented on versioned_docs/version-1.2/how_to_guides/format_output.mdx
> +`--output -` and `--format` can not be used at the same time due to conflicts.
Accepted and updated

2024-07-02 16:17 UTC, merged