doc: update installation guide to v1.2.1
oras-project/oras-www pull request #435
Opened 2024-12-06 02:32 UTC by FeynmanZhou

Update installation guide to v1.2.1 as the vote is passed in https://github.com/oras-project/oras/pull/1563

2024-12-06 03:44 UTC, qweeah requested changes

2024-12-06 03:44 UTC, qweeah commented on versioned_docs/version-1.2/installation.mdx
>  Git commit:     dcef719e208a9b226b15bc6512ad729a7dd93270
```suggestion
Git commit:     a0228556766b6276010d8feb937af512e8a50808
```

2024-12-06 03:44 UTC, qweeah commented on versioned_docs/version-1.2/installation.mdx
>  Go version:     go1.22.3
```suggestion
Go version:     go1.23.4
```

2024-12-08 23:35 UTC, qweeah approved these changes
LGTM but IANAM

2024-12-10 02:21 UTC, FeynmanZhou commented on versioned_docs/version-1.2/installation.mdx
> +This guide demonstrates the installation steps of ORAS CLI `v1.2.1` on different platforms.
Hi @TerryHowe , I think it does make sense to explicitly state the version number at the beginning of the installation guide. Without this information, users might not be aware of which version will be installed using Homebrew, Winget below. 

Adding a version number here will not introduce too much maintenance cost.

2024-12-11 00:20 UTC, TerryHowe approved these changes
/lgtm

2024-12-11 00:20 UTC, TerryHowe commented on versioned_docs/version-1.2/installation.mdx
> +This guide demonstrates the installation steps of ORAS CLI `v1.2.1` on different platforms.
Sounds good

2024-12-12 08:17 UTC, merged